---
- name: Enable root ssh
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin without-password'
    line: 'PermitRootLogin yes'
  notify:
  - restart ssh

- name: Change root password
  become: true
  when: ssh.root_password is defined
  user:
    name: root
    password: "{{ ssh.root_password }}"

- name: Create ssh user
  become: true
  when: ssh.users is defined and ssh.passwords is defined
  user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    state: present
    shell: /bin/bash   
  with_together:
    - "{{ ssh.users }}"
    - "{{ ssh.passwords }}"
