---
- name: Install MySQL
  apt: name={{item}} update_cache=yes state=present
  with_items:
  - python-mysqldb
  - mysql-server
  notify:
  - start MySQL

- name: Create MySQL root user
  mysql_user: 
    name: "{{mysql.user}}" 
    password: "{{mysql.password}}"
    priv: '*.*:ALL' 
    state: present