---
- name: Install MySQL
  apt: name={{item}} update_cache=yes state=present
  with_items:
  - python-mysqldb
  - php5-mysql
  - mysql-server

- name: Create MySQL DB user(s)
  mysql_user: 
    name: "{{ item.0 }}" 
    password: "{{ item.1 }}"
    priv: '*.*:ALL' 
    state: present
  with_together:
    - "{{ mysql.user }}" 
    - "{{ mysql.password }}"
  
