---

- name: Install php-mysql
  become: true
  apt: name=php-mysql state=present
  notify: 
    - restart apache2

- name: Copy PHP deployments
  copy:
    src: "{{item}}.tar.gz"
    dest: "/tmp/{{item}}.tar.gz"
  with_items: "{{php.deployments}}"

- name: Unzip PHP deployments
  unarchive:
    src: "/tmp/{{item}}.tar.gz"
    dest: /
    remote_src: yes
  with_items: "{{php.deployments}}"
 
- name: Remove PHP deployments zipfile
  file:
    path: "/tmp/{{item}}.tar.gz"
    state: absent
  with_items: "{{php.deployments}}"

- name: Prikazi trenutni radni direktorijum
  command: pwd
  register: current_dir

- debug:
    msg: "Trenutni direktorijum je {{ current_dir.stdout }}"

- name: Run Composer for PHP deployments
  command: echo tusam && ls && pwd
  with_items: "{{ php.deployments }}"

- name: Update PHP Composer database connections to use MySQL password
  lineinfile:
    path: "/var/www/html/{{item}}/app/Database/Connection.php"
    regexp: "^\\s*const DB_PASS = 'password';\\s*$"
    line: "const DB_PASS = '{{mysql.root.0}}';"
  with_items: "{{ php.deployments }}"

