---
- name: Update apt
  become: true
  apt: update_cache=yes

- name: Install php5
  become: true
  apt: name=libapache2-mod-php5 state=present
 
- include_tasks: composer.yml
- include_tasks: clone-repo.yml

- name: Remove index.html
  file:
    state: absent
    path: /var/www/html/index.html
